language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  
env:

before_script:
 - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev --no-interaction --prefer-source

script:
 - mkdir -p build/logs
 - phpunit --configuration ./test/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v --exclude-no-stmt
