language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  
env:

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --configuration ./test/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - CODECLIMATE_REPO_TOKEN=61dee9290d175e093ff6f2569544d8aeb4f58af2ea941fe91753e7c351f8a20b ./vendor/bin/test-reporter
 - php vendor/bin/coveralls -v
